default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: african_queen_kitchen_development


test:
  <<: *default
  database: african_queen_kitchen_test


production:
  <<: *default
  database: african_queen_kitchen_production
  username: african_queen_kitchen
  password: <%= ENV["AFRICAN_QUEEN_KITCHEN_PASSWORD"] %>